# Generated by Django 6.0.1 on 2026-01-14 08:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Protein", "Protein"),
                            ("Creatine", "Creatine"),
                            ("Bars", "Bars"),
                            ("Pre-workout", "Pre-workout"),
                        ],
                        max_length=100,
                    ),
                ),
                ("stock_quantity", models.IntegerField(default=0)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buyer_name", models.CharField(max_length=200)),
                ("buyer_contact", models.CharField(max_length=15)),
                ("quantity_sold", models.IntegerField()),
                ("sale_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "total_profit",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "supplement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplements.supplement",
                    ),
                ),
            ],
        ),
    ]
